kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

name: my-app-cluster

nodes:
  - role: control-plane
    extraPortMappings:
      # NodePort for API service
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP
